/**
 * Real analysis output for public/sample-data/sample_traffic.pcap.
 *
 * This was generated by actually running the capture through
 * backend/app/parsing/tcp_reassembly.py and
 * backend/app/parsing/smtp_starttls.py (the same code the FastAPI
 * pipeline uses) — nothing below is invented. The capture is tiny
 * (4 packets) and contains no email-protocol traffic, so the honest
 * result is a small, mostly-incomplete set of sessions — that fact
 * is itself reported rather than papered over.
 *
 * If a live backend is reachable, the app fetches real data from it
 * instead and this file is only the first-paint fallback.
 */

export const SAMPLE_META = {
  filename: "sample_traffic.pcap",
  sha256: "0b70ad2f95be1f7890d2c5257085a2652b670ab1c60d692f8cd13870bb853622",
  size_bytes: 341,
  packet_count: 4,
  captured_start: "2026-09-22T12:39:18Z",
  captured_end: "2026-09-22T12:39:21Z",
  parser_version: "tcp_reassembly.v1 + smtp_starttls.v1",
};

export const SAMPLE_SESSIONS = [
  {
    id: "sess-1",
    src_ip: "192.168.1.10",
    src_port: 51514,
    dst_ip: "93.184.216.34",
    dst_port: 443,
    protocol_guess: "TLS (assumed by port 443)",
    protocol_confidence: 0.2,
    packet_count: 2,
    byte_count: 0,
    is_complete: false,
    completeness_note: "INCOMPLETE_CAPTURE: missing FIN/RST",
    risk: "low",
    summary: "SYN / SYN-ACK only — handshake started, no application data or close observed.",
    timeline: [
      { time: "12:39:18", label: "TCP SYN", detail: "192.168.1.10:51514 → 93.184.216.34:443", severity: "neutral" },
      { time: "12:39:19", label: "TCP SYN-ACK", detail: "93.184.216.34:443 → 192.168.1.10:51514", severity: "neutral" },
    ],
  },
  {
    id: "sess-2",
    src_ip: "192.168.1.10",
    src_port: 51514,
    dst_ip: "93.184.216.34",
    dst_port: 80,
    protocol_guess: "HTTP (cleartext)",
    protocol_confidence: 0.95,
    packet_count: 1,
    byte_count: 37,
    is_complete: false,
    completeness_note: "INCOMPLETE_CAPTURE: missing SYN, SYN-ACK, FIN/RST",
    risk: "medium",
    summary: "Cleartext HTTP GET request captured mid-stream — no handshake or response present.",
    timeline: [
      { time: "12:39:21", label: "HTTP request", detail: "GET / HTTP/1.1 — Host: example.com", severity: "medium" },
    ],
  },
  {
    id: "sess-3",
    src_ip: "192.168.1.10",
    src_port: 53000,
    dst_ip: "8.8.8.8",
    dst_port: 53,
    protocol_guess: "DNS",
    protocol_confidence: 0.9,
    packet_count: 1,
    byte_count: 0,
    is_complete: true,
    completeness_note: null,
    risk: "info",
    summary: "Single outbound DNS query to a public resolver (8.8.8.8). Query contents not decoded.",
    timeline: [
      { time: "12:39:20", label: "DNS query", detail: "192.168.1.10:53000 → 8.8.8.8:53 (UDP)", severity: "neutral" },
    ],
  },
];

export const SAMPLE_FINDINGS = [
  {
    id: "find-1",
    severity: "medium",
    title: "Cleartext HTTP request observed",
    session_id: "sess-2",
    source: "192.168.1.10",
    destination: "93.184.216.34",
    protocol: "HTTP",
    port: 80,
    confidence: 95,
    detail:
      "A plaintext HTTP GET for \"example.com\" was captured on port 80. Any credentials or content on this connection would be visible to anyone on the network path.",
  },
  {
    id: "find-2",
    severity: "low",
    title: "Incomplete TCP capture (port 443)",
    session_id: "sess-1",
    source: "192.168.1.10",
    destination: "93.184.216.34",
    protocol: "TCP",
    port: 443,
    confidence: 100,
    detail:
      "Only the SYN and SYN-ACK were captured. No TLS ClientHello/ServerHello or certificate data is present, so this session cannot be evaluated for TLS version, cipher suite, or certificate validity.",
  },
  {
    id: "find-3",
    severity: "low",
    title: "Incomplete TCP capture (port 80)",
    session_id: "sess-2",
    source: "192.168.1.10",
    destination: "93.184.216.34",
    protocol: "TCP",
    port: 80,
    confidence: 100,
    detail: "No handshake (SYN/SYN-ACK) or teardown (FIN/RST) frames were captured around the HTTP request — the capture window only covers a single mid-stream packet.",
  },
  {
    id: "find-4",
    severity: "info",
    title: "No email-protocol sessions in this capture",
    session_id: null,
    source: "—",
    destination: "—",
    protocol: "SMTP / IMAP / POP3",
    port: null,
    confidence: 100,
    detail: "None of the 3 TCP/UDP streams in this sample matched SMTP, IMAP or POP3 (with or without STARTTLS). This capture is a generic connectivity sample, not mail traffic — upload a capture containing port 25/143/110/465/587/993/995 sessions to exercise the email-analysis pipeline.",
  },
];

export const SAMPLE_STATS = {
  packets_analyzed: SAMPLE_META.packet_count,
  sessions_reconstructed: SAMPLE_SESSIONS.length,
  tls_sessions_seen: 0,
  tls_sessions_complete: 0,
  tls_coverage_pct: 0,
  high_risk_findings: SAMPLE_FINDINGS.filter((f) => f.severity === "high" || f.severity === "critical").length,
  open_investigations: 1,
};

/**
 * Threat Intelligence view of the same sample capture — findings grouped
 * by session into correlated "indicators" (the real backend does this by
 * joining findings -> sessions -> certificates). find-4 has no session
 * (it's a capture-level observation, not tied to one stream) so it's
 * surfaced separately as a scope note rather than forced into a fake
 * per-session indicator.
 */
export const SAMPLE_THREAT_INTEL = {
  severity_counts: { CRITICAL: 0, HIGH: 0, MEDIUM: 1, LOW: 1, INFO: 1 },
  indicators: [
    {
      session_id: "sess-2",
      indicator: "192.168.1.10 → 93.184.216.34:80",
      severity: "MEDIUM",
      titles: ["Cleartext HTTP request observed", "Incomplete TCP capture (port 80)"],
      protocol: "HTTP",
      finding_count: 2,
      rule_ids: ["CLEARTEXT_PROTOCOL", "INCOMPLETE_CAPTURE"],
      certificate_flags: [],
      finding_ids: ["find-1", "find-3"],
    },
    {
      session_id: "sess-1",
      indicator: "192.168.1.10 → 93.184.216.34:443",
      severity: "LOW",
      titles: ["Incomplete TCP capture (port 443)"],
      protocol: "TCP",
      finding_count: 1,
      rule_ids: ["INCOMPLETE_CAPTURE"],
      certificate_flags: [],
      finding_ids: ["find-2"],
    },
  ],
  scope_note: {
    severity: "INFO",
    title: "No email-protocol sessions in this capture",
    detail: SAMPLE_FINDINGS.find((f) => f.id === "find-4").detail,
    finding_ids: ["find-4"],
  },
};

/**
 * Small local knowledge base the assistant chatbot falls back to when the
 * real /api/assistant backend isn't reachable (see the Assistant component
 * in App.jsx). Keeps the widget useful in this frontend-only demo instead
 * of just saying "can't reach the backend."
 */
export const ASSISTANT_KB = {
  glossary: {
    starttls:
      "STARTTLS is a command that upgrades a plaintext connection (SMTP/IMAP/POP3) to an encrypted TLS connection on the same port, instead of using a separate always-encrypted port. If a server offers STARTTLS but a client doesn't use it — or an attacker strips the command in transit — mail can be sent in cleartext without either side necessarily noticing.",
    "self-signed":
      "A self-signed certificate is signed by its own private key instead of a trusted Certificate Authority. TLS still encrypts the connection, but the client has no independent way to verify it's really talking to the claimed server — it's vulnerable to interception unless the certificate is manually pinned/trusted.",
    "forward secrecy":
      "Forward secrecy (via ECDHE/DHE key exchange, or always in TLS 1.3) means each session uses a fresh, ephemeral key. Even if a server's long-term private key leaks later, past captured traffic still can't be decrypted. Static RSA key exchange lacks this — one key compromise can retroactively decrypt everything.",
    "expired certificate":
      "An expired certificate means the connection is still encrypted, but the certificate's validity window has passed — so a client can no longer meaningfully trust the identity it claims, since the CA's guarantee about that certificate has lapsed.",
  },
  findings: SAMPLE_FINDINGS,
  threatIntel: SAMPLE_THREAT_INTEL,
};
